title: 'Expo Settings'
data:
  event_dates:
    -
      id: lzhclgll
      expo_date: '2024-08-05'
      expo_open_time: '09:00'
      expo_close_time: '17:00'
    -
      id: lzhcljrw
      expo_date: '2024-08-06'
      expo_open_time: '09:00'
      expo_close_time: '17:00'
    -
      id: lzhclnd8
      expo_date: '2024-08-07'
      expo_open_time: '09:00'
      expo_close_time: '16:00'
